name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - tools/*
  pull_request:
    paths-ignore:
      - README.md
      - tools/*

env:
  CONFIGURATION: RelWithDebInfo

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - name: Install packages
        run: |
          choco install wget 7zip cmake
      - name: Install Pawn compiler
        run: |
          wget https://github.com/Zeex/pawn/releases/download/20150412/pawnc-3.10.20150412-windows.zip
          7z x pawnc-3.10.20150412-windows.zip
          Add-Content $env:GITHUB_PATH "$(pwd)\pawnc-3.10.20150412-windows\bin"
      - name: Install Plugin Runner
        run: |
          wget https://github.com/Zeex/samp-plugin-runner/releases/download/v1.3/plugin-runner-1.3-win32.zip
          7z x plugin-runner-1.3-win32.zip
          Add-Content $env:GITHUB_PATH "$(pwd)\plugin-runner-1.3-win32"

      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=$env:CONFIGURATION .. -G "Visual Studio 16 2019" -A Win32 -T v141_xp
      - name: Build
        working-directory: build
        run: |
          cmake --build . --config $env:CONFIGURATION
          cmake --build . --config $env:CONFIGURATION --target package
      - name: Run tests
        working-directory: build
        run: |
          ctest --build-config $env:CONFIGURATION

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: build/crashdetect-*-win32.zip

  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - name: Install packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install gcc-7-multilib g++-7-multilib cmake
      - name: Install Pawn compiler
        run: |
          wget https://github.com/Zeex/pawn/releases/download/20150412/pawnc-3.10.20150412-linux.tar.gz
          sudo tar xvf pawnc-3.10.20150412-linux.tar.gz --strip-components=1 -C /usr/local
          sudo ldconfig
      - name: Install Plugin Runner
        run: |
          wget https://github.com/Zeex/samp-plugin-runner/releases/download/v1.3/plugin-runner-1.3-linux.tar.gz
          sudo tar xvf plugin-runner-1.3-linux.tar.gz --strip-components=1 -C /usr/local

      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=$CONFIGURATION -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32
      - name: Build
        working-directory: build
        run: |
          make
          make package
      - name: Run tests
        working-directory: build
        run: |
          make test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-linux
          path: build/crashdetect-*-linux.tar.gz
